### ISSUE TITLE
Bug: CSS of the site is not working properly

### ISSUE THREAD

**Issue by vikhyat187** [Freedium-cfd/web#14]
Hi @ZhymabekRoman, This ticket aims to report an issue which is related to the CSS of the site https://freedium.cfd/ not working properly.

Screenshot:
<img width="1440" alt="image" src="https://github.com/Freedium-cfd/web/assets/52795644/d46662ed-16dc-44cc-9294-747d42671d6d">

**Comment by ZhymabekRoman** [comment]
Thanks! Can you show all network requests and console tab in screenshot?

**Comment by vikhyat187** [comment]
Its fixed now.

**Comment by ZhymabekRoman** [comment]
I think the problem was in the CDN side.
