### ISSUE TITLE
CSS issue in "Reporting a Problem" modal.

### ISSUE THREAD

**Issue by UddeshJain** [Freedium-cfd/web#15]
Header is hiding some part of "Report a Problem" modal.

z-index order is not proper and it's causing this problem.

Screenshot:-

<img width="1440" alt="Screenshot 2024-01-12 at 8 46 36 PM" src="https://github.com/Freedium-cfd/web/assets/39882428/dba1e2f0-b6d9-4026-a630-f6cdd70c463a">

**Comment by ZhymabekRoman** [comment]
Fixed
