### ISSUE TITLE
Codelines are rendered one by one

### ISSUE THREAD

**Issue by GuyKh** [Freedium-cfd/web#18]
If I may report an issue, when rendering code - it renders line by line separately.

e.g.
https://medium.com/geekculture/home-assistant-docker-zigbee2mqtt-3d8e0ba02d10

![image](https://github.com/Freedium-cfd/web/assets/3136012/78548e83-1d21-4c20-b7dc-a11d27772ee5)

**Comment by ZhymabekRoman** [comment]
Thanks, I know about that problem, but I don't know how to correctly implement support for code block, because Medium's API returns these blocks as separate element.

**Comment by ZhymabekRoman** [comment]
Feel free to open PR!

**Comment by GuyKh** [comment]
@ZhymabekRoman - first of all, it's good to have an issue open for following this.
I'll try to peek, I'm a bit short on time lately, but I'll give it a shot.

**Comment by ZhymabekRoman** [comment]
Good looking code block example - https://freedium.cfd/https://medium.com/@clemensjarnach/creating-toggle-lists-in-obsidian-9c3dc16a25a1

**Comment by ZhymabekRoman** [comment]
Fixed, thank you for using Freedium!
