### ISSUE TITLE
The "bad news" message on freedium.cfd can't be closed on IOS

### ISSUE THREAD

**Issue by joeczucha** [Freedium-cfd/web#22]
As above, using Safari on IOS 17. 

The close button doesn't seem to work on IOS so you can't read the article that you've freedium'd.

**Comment by ZhymabekRoman** [comment]
Can't reproduce error, using Appetize. Can you record and send screen video?

**Comment by ZhymabekRoman** [comment]
Thanks! Fixed.

**Comment by joeczucha** [comment]
Yep that's working great again now, thanks very much ☺️
