### ISSUE TITLE
Freedium android app

### ISSUE THREAD

**Issue by ys-pro-duction** [Freedium-cfd/web#23]
[Freedium app](https://github.com/ys-pro-duction/Freedium-app)

**Comment by ZhymabekRoman** [comment]
Wow, thank you! Very interesting.

**Comment by ramazansancar** [comment]
Firefox on mobile now offers add-on support. Here it will be easy to use with the relevant plugin. I recommend.

https://addons.mozilla.org/en-US/firefox/addon/redirector/
