### ISSUE TITLE
Freedium not working

### ISSUE THREAD

**Issue by Nagarajan1990** [Freedium-cfd/web#24]
Not able to access freedium via url

**Comment by Nagarajan1990** [comment]
![Screenshot_2024-07-17-11-50-39-586_com.android.chrome.jpg](https://github.com/user-attachments/assets/be5609ea-0ecd-4aa8-ba4f-130f888e921b)

**Comment by Nagarajan1990** [comment]
Tracked as part of #16 hence closing this

**Comment by FreqHead** [comment]
@ZhymabekRoman You're the best man, thank you so much.
