### ISSUE TITLE
Issue: Error During Local Host Setup Using Docker

### ISSUE THREAD

**Issue by wm-jenildgohel** [Freedium-cfd/web#25]
### **While attempting to set up Freedium locally using Docker, I encountered an error related to ASL logging and credentials. The command used and the error message are detailed below.**

**Steps to Reproduce:**
1. Clone the Freedium repository.
2. Run the following command to set up the environment:
   ```bash
   sudo docker-compose -f prod.docker-compose.yml up
   ```
3. The following error occurs:

   ```
   2024/08/14 12:03:53 must use ASL logging (which requires CGO) if running as root
   [+] Running 0/2
   [+] Running 0/2ling                                                                                               0.2s 
    ⠸ autoheal Pulling                                                                                               0.3s 
    ⠸ dragonfly Pulling                                                                                              0.3s 
   error getting credentials - err: exit status 1, out: ``
   ```

**Expected Behavior:**
The Docker containers should start up without any issues, allowing for a successful local setup of the Freedium environment.

**Actual Behavior:**
The setup fails with an error related to ASL logging and credential retrieval.

**Environment:**
- OS: MacOS Sonama
- Docker version: 25.0.3, build 4debf41
- Docker Compose version: v2.24.6-desktop.1

**Possible Solutions:**
- Investigate the requirement for ASL logging when running as root.
- Review and troubleshoot the credentials issue mentioned in the error.

**Additional Information:**
If there are any specific configurations or environment variables required for the setup, please provide them in the documentation.

**Comment by ZhymabekRoman** [comment]
This problem not related to the Freedium: https://stackoverflow.com/questions/71770693/error-saving-credentials-error-storing-credentials-err-exit-status-1-out

**Comment by ZhymabekRoman** [comment]
FYI: https://github.com/docker/docker-credential-helpers/issues/140#issuecomment-1149610603
