### ISSUE TITLE
It seems under xss attack.

### ISSUE THREAD

**Issue by shuvo5cis** [Freedium-cfd/web#27]
While trying to enter an write-ups it’s showing a pop up like reflected xss. Also it’s not showing the full article. Check it now.

![1000029390.jpg](https://github.com/user-attachments/assets/1361ee52-2468-4ca2-b139-9ee3955bba52)

**Comment by ZhymabekRoman** [comment]
Yes, it is. I'm working on a new web frontend and a new backend, although it will take a while. I can't estimate how much would be required to finish rewriting the whole project...

**Comment by 1ikeadragon** [comment]
I was just about to open an issue for the same. I suggest adding a disclaimer on the site as threat actors can hide payload at the bottom of a sub-only article which will not be caught by the user but executed on client.

**Comment by ZhymabekRoman** [comment]
Fixed
