### ISSUE TITLE
Chrome browser extension

### ISSUE THREAD

**Issue by wywywywy** [Freedium-cfd/web#6]
Hi.

I've published a Chrome extension to easily open a Medium article in Freedium here - https://chrome.google.com/webstore/detail/open-in-freedium/giibjnmcmkglpdichdiabecdkeefknak

I'll work on publishing it to the Firefox store next.

Then I'll tidy the code up and open source it right after that.

Hope it helps.

**Comment by wywywywy** [comment]
Firefox addon is live - https://addons.mozilla.org/en-GB/firefox/addon/open-in-freedium/

**Comment by ZhymabekRoman** [comment]
Can you release the extension's source code under an open-source license?

With Sirrenity,
Roman

**Comment by wywywywy** [comment]
Will do this weekend. I've been meaning to tidy every up then put an MIT licence on it.

**Comment by wywywywy** [comment]
Source code now available here: https://github.com/wywywywy/freedium-browser-extension

**Comment by ZhymabekRoman** [comment]
Can we move that repository to Freedium organization?

With Sirrenity,
Roman

**Comment by ZhymabekRoman** [comment]
Head over to the repository settings:

Then, under “Danger Zone,” click “Transfer.”

Of course, this is a dangerous process. Make absolutely sure that the username/organization name is 100% correct, as it doesn’t validate the user’s profile before you press the big red button, despite requiring you to type the repo name out to confirm.

Source: https://cobrasupernova.pages.dev/posts/how-to-transfer-a-github-repository-to-your-organization-or-another-user-/

**Comment by ZhymabekRoman** [comment]
Okay. Yeah, that's another issue. 

Thanks for your help. I added a link to the extensions in the README files
