### ISSUE TITLE
Medium articles with custom domains not working

### ISSUE THREAD

**Issue by papadonut9** [Freedium-cfd/web#7]
When I try to open a medium article with a custom domain, there is no redirect. I get a `about: blank`.

for example [this link](https://bootcamp.uxdesign.cc/how-i-created-my-first-comic-book-using-chatgpt-and-midjourney-a0a930b35f8e)

**Comment by ZhymabekRoman** [comment]
Experiencing no issues. Try paste the link to the Freedium main page: https://freedium.cfd/

**Comment by ZhymabekRoman** [comment]
Medium has a very high rate limit on their API side, so it looks like something unexpected occurred

**Comment by ZhymabekRoman** [comment]
Article is now loading
